language: java

# Testing against multiple JDKs.
jdk:
#  - oraclejdk8
#  - oraclejdk11
  - openjdk8
#  - openjdk11

branches:
  only:
    - dev

# Home directory in Travis CI server.
cache:
  directories:
    - "$HOME/.m2/repository" # Maven
    - "$HOME/.gradle" # Gradle

script: "./mvnw clean install"

# Codecov
after_success:
  - bash < (curl -s https://codecov.io/bash)

# Notification when Travis CI is done.
notifications:
  email:
    recipients:
      - hackeres123@gmail.com
